<a href="https://colab.research.google.com/github/miarangoa/Data-Science-FEM-Study-Group/blob/master/Lineal_Algebra_Practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1.

* Print the sum of matrixes A and B

$$ A =
\left(\begin{array}{cc} 
1 & 2\\
3 & 4\\
5 & 6
\end{array}\right) + B =
\left(\begin{array}{cc} 
6 & 5\\
4 & 3\\
2 & 1 
\end{array}\right)
$$ 

In [19]:
# Answer 1.
'Your code here'

import numpy as np
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[6, 5], [4, 3], [2, 1]])
print("A + B es igual a:", A+B, sep = "\n")

A + B es igual a:
[[7 7]
 [7 7]
 [7 7]]


# Question 2

* Print the sum of matrix + scalar.

$$ M =
\left(\begin{array}{cc} 
6 & 3\\
9 & 5\\
4 & 8
\end{array}\right) + N =
\left(\begin{array}{cc} 
2.5 \\ 
\end{array}\right)
$$ 

In [20]:
# Answer 2.
'Your code here'
M = np.array([[6, 3], [9, 5], [4, 8]])
N = 2.5
print("M + N es igual a:", M+N, sep = "\n")

M + N es igual a:
[[ 8.5  5.5]
 [11.5  7.5]
 [ 6.5 10.5]]


# Question 3.

* Print the transposed matrix of  $J$  -->  $J^t$. 

$$ J =
\left(\begin{array}{cc} 
9 & 2 & 3\\
3 & 7 & 4 \\
5 & 6 & 9
\end{array}\right) 
$$ 

In [21]:
# Answer 3.
'Your code here'
J = np.array([[9, 2, 3], [3, 7, 4], [5, 6, 9]])
print("La transpuesta de J es igual a:", J.T, sep = "\n")

La transpuesta de J es igual a:
[[9 3 5]
 [2 7 6]
 [3 4 9]]


# Question 4.

* For the $ J ^ t $ matrix, calculate your transpose to obtain the original matrix J. 

$$ J =
\left(\begin{array}{cc} 
9 & 2 & 3\\
3 & 7 & 4 \\
5 & 6 & 9
\end{array}\right) 
$$ 

In [22]:
# Answer 4.
'Your code here'
print("La transpuesta de Jt es igual a:", (J.T).T, sep = "\n")

La transpuesta de Jt es igual a:
[[9 2 3]
 [3 7 4]
 [5 6 9]]


# Question 5.

* 
What are the missing values? 

$$
\left(\begin{array}{cc} 
? & 2\\
0 & 2
\end{array}\right)
\left(\begin{array}{cc} 
1 & 0 \\ 
1 & ? 
\end{array}\right)
$$ 

 * so that the answer is like this:
$
\left(
 \begin {array}{ll} 
1 & 0 \\
0   & 0
\end{array}
\right)
$

- [ A ] = 1 y 1
- [ B ] = 0 y 1
- [ C ] = 1 y 0
- [ D ] = 0 y 0

*  Print the result and the answer.

In [23]:
# Answer 5.
'your code here'
A1 = np.array([[1, 2], [0, 2]])
A2 = np.array([[1, 0], [1, 1]])
B1 = np.array([[0, 2], [0, 2]])
B2 = np.array([[1, 0], [1, 1]])
C1 = np.array([[1, 2], [0, 2]])
C2 = np.array([[1, 0], [1, 0]])
D1 = np.array([[0, 2], [0, 2]])
D2 = np.array([[1, 0], [1, 0]])

print("A:", A1.dot(A2), sep = "\n")
print("\nB:", B1.dot(B2), sep = "\n")
print("\nC:", C1.dot(C2), sep = "\n")
print("\nD:", D1.dot(D2), sep = "\n")

A:
[[3 2]
 [2 2]]

B:
[[2 2]
 [2 2]]

C:
[[3 0]
 [2 0]]

D:
[[2 0]
 [2 0]]


# Question 6.
* ¿ What is the dot product matrixes  $L$ y $K$ = : ?

$$ L =
\left(\begin{array}{cc} 
3 & 5 \\
7 & 1 \\
\end{array}\right) K =
\left(\begin{array}{cc} 
3 & 12  \\
6 & 4  \\
\end{array}\right)
$$ 

In [24]:
# Answer 6.
'your code here'
L = np.array([[3, 5], [7, 1]])
K = np.array([[3, 12], [6, 4]])
print("El producto punto de L y K es igual a:", L.dot(K), sep = "\n")

El producto punto de L y K es igual a:
[[39 56]
 [27 88]]


# Question 7.

* ¿ What is the determinant of the following matrix  ? (Print the answer)

$
\left(
\begin {array}{ll} 
1 & 2 & 0 \\
1 & 2 & 0 \\
0 & 1 & 1 \\
\end{array}
\right)
$

- [ A ] = 1 
- [ B ] = 0 
- [ C ] = 5
- [ D ] = -5



In [25]:
# Answer 7.
'your code here'
a = np.array([[1, 2, 0], [1, 2, 0], [0, 1, 1]])
print("El determinante de la matriz es igual a:", np.linalg.det(a), sep = "\n")

El determinante de la matriz es igual a:
0.0


# Question 8.

* ¿ What is the determinant of the following matrix ? (Print the answer)

$
\left(
\begin {array}{ll} 
0 & 1 & 1 \\
1 & 0 & 0 \\
0 & 0 & 1 \\
\end{array}
\right)
$

- [ A ] = 0 
- [ B ] = -1 
- [ C ] = 3
- [ D ] = 1


In [26]:
# Answer 8.
'your code here'
b = np.array([[0, 1, 1], [1, 0, 0], [0, 0, 1]])
print("El determinante de la matriz es igual a:", np.linalg.det(b), sep = "\n")

El determinante de la matriz es igual a:
-1.0


# Question 9

* ¿What is the missing value?
$$ 
\left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}\right) 
\left(\begin{array}{cc} 
0 \\ 
? \\
16 \\
\end{array}\right) =
\left(\begin{array}{cc} 
4 \\ 
10 \\
16 \\
\end{array}\right)
$$ 

In [31]:
matriz_ = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector_ = np.array ([[0], [2], [0]])
multiplicacion = matriz_.dot(vector_)
print("El valor abajo del faltante no es 16 sino 0*")
print("\n", "Validación: ", multiplicacion, sep = "\n")
print("\n", "El valor faltante es: 2")

El valor abajo del faltante no es 16 sino 0*


Validación: 
[[ 4]
 [10]
 [16]]

 El valor faltante es: 2
